<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/

/**
 * Implements hook_menu().
 */
 
function HSSAdmin_menu() {
	$items["admincp/type"] = array(
		"title" => "Kiểu nội dung",
		"description" => "HSS Type",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/category"] = array(
		"title" => "Danh mục",
		"description" => "HSS Category",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/ads"] = array(
		"title" => t('Quảng cáo'),
		"description" => "HSS Ads",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/contact"] = array(
		"title" => t('Thông tin liên hệ'),
		"description" => "HSS Contact",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/info"] = array(
		"title" => t('Cài đặt'),
		"description" => "HSS Info",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/supportonline"] = array(
		"title" => t('Nick hỗ trợ trực tuyến'),
		"description" => "HSS Support online",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items['admincp/product'] = array(
        'title' => t('Sản phẩm'),
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admincp/order"] = array(
		"title" => t('Đơn hàng'),
		"description" => "HSS Order",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/news"] = array(
		"title" => t('Tin tức'),
		"description" => "HSS News",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/users"] = array(
		"title" => t('Quản lý người dùng'),
		"description" => "HSS Users",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	/*comment*/
	$items["admincp/ajaxupComment"] = array(
		"title" => t('Ajaxup Comment'),
		"description" => "HSS Comment",
		'page callback' => 'ajaxupComment',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/ajaxdeleteComment"] = array(
		"title" => t('Ajaxdel Comment'),
		"description" => "HSS Comment",
		'page callback' => 'ajaxdeleteComment',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/popupAjaxAllComment"] = array(
		"title" => t('AjaxAll Comment popup'),
		"description" => "HSS Comment popup",
		'page callback' => 'popupAjaxAllComment',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items["admincp/ajaxAllDetailOrder"] = array(
		"title" => t('AjaxAll DetalOrder'),
		"description" => "HSS DetalOrder",
		'page callback' => 'ajaxAllDetailOrder',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/ajaxUpdateStatus"] = array(
		"title" => t('HSS Upload status'),
		"description" => "HSS Upload status",
		'page callback' => 'ajaxUpdateStatus',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	$items["admincp/recyclebin"] = array(
		"title" => t('HSS RecycleBin'),
		"description" => "HSS RecycleBin",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
  return $items;
}

/**
 * Implements hook_theme().
 */
function HSSAdmin_theme() {
    return array(
		'type' => array(
            'template' => 'View/tpl/type/type'
        ),
        'type-form' => array(
            'template' => 'View/tpl/type/type-form'
        ),
		'category' => array(
            'template' => 'View/tpl/category/category'
        ),
        'category-form' => array(
            'template' => 'View/tpl/category/category-form'
        ),
        'product' => array(
            'template' => 'View/tpl/product/product'
        ),
        'product-form' => array(
            'template' => 'View/tpl/product/product-form'
        ),
        'contact' => array(
            'template' => 'View/tpl/contact/contact'
        ),
        'contact-form' => array(
            'template' => 'View/tpl/contact/contact-form'
        ),
		'ads' => array(
            'template' => 'View/tpl/ads/ads'
        ),
        'ads-form' => array(
            'template' => 'View/tpl/ads/ads-form'
        ),
		'info' => array(
            'template' => 'View/tpl/info/info'
        ),
        'info-form' => array(
            'template' => 'View/tpl/info/info-form'
        ),
        'supportonline' => array(
            'template' => 'View/tpl/supportonline/supportonline'
        ),
        'supportonline-form' => array(
            'template' => 'View/tpl/supportonline/supportonline-form'
        ),
        'users' => array(
            'template' => 'View/tpl/users/users'
        ),
        'users-form' => array(
            'template' => 'View/tpl/users/users-form'
        ),
		'permission' => array(
            'template' => 'View/tpl/permission/permission'
        ),
        'permission-form' => array(
            'template' => 'View/tpl/permission/permission-form'
        ),
        'module' => array(
            'template' => 'View/tpl/module/module'
        ),
        'module-form' => array(
            'template' => 'View/tpl/module/module-form'
        ),
        'showfields-form' => array(
            'template' => 'View/tpl/showfields/showfields-form'
        ),
        'news' => array(
            'template' => 'View/tpl/news/news'
        ),
        'news-form' => array(
            'template' => 'View/tpl/news/news-form'
        ),
        'order' => array(
            'template' => 'View/tpl/order/order'
        ),
        'order-form' => array(
            'template' => 'View/tpl/order/order-form'
        ),
        'recyclebin' => array(
            'template' => 'View/tpl/recyclebin/recyclebin'
        ),
        'recyclebin-form' => array(
            'template' => 'View/tpl/recyclebin/recyclebin-form'
        ),
    );
}

/**
 * Implements hook_permission().
 */
function HSSAdmin_permission() {
  return array(
    'access protected HSS Admin' => array(
      'title' => t('access protected HSS Admin'),
    ),
  );
}
/**
 * Implements hook_init().
 */
function HSSAdmin_init(){
	$uri = request_uri();
	if(preg_match("/(\/admincp)/", $uri)!=0){
		$files = array(
			/*type*/
			'Model/typeModel.php',
			'Controller/typeController.php',
			/*category*/
			'Model/categoryModel.php',
			'Controller/categoryController.php',
			/*contact*/
			'Model/contactModel.php',
			'Controller/contactController.php',
			/*ads*/
			'Model/adsModel.php',
			'Controller/adsController.php',
			/*setup*/
			'Model/infoModel.php',
			'Controller/infoController.php',
			/*support online*/
			'Model/supportonlineModel.php',
			'Controller/supportonlineController.php',
			/*users*/
			'Model/usersModel.php',
			'Controller/usersController.php',
			/*permission*/
			'Model/permissionModel.php',
			'Controller/permissionController.php',
			/*module*/
			'Model/moduleModel.php',
			'Controller/moduleController.php',
			/*show fields*/
			'Model/showFieldsModel.php',
			'Controller/showFieldsController.php',
			/*news*/
			'Model/newsModel.php',
			'Controller/newsController.php',
			/*product*/
			'Model/productModel.php',
			'Controller/productController.php',
			/*order*/
			'Model/orderModel.php',
			'Controller/orderController.php',
			/*comment*/
			'Controller/commentController.php',
			/*recycleBin*/
			'Model/RecycleBinModel.php',
			'Controller/recycleBinController.php',
			/*js*/
			'View/js/admin.js',
			'View/css/adm.css',
		);
		clsLoader::load('HSSAdmin', $files);
	}
}