<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/
function HSSPageStatics_menu(){
    $items = array();
    
    #item in category
    $clsCategory = new Category();
    $arr_link = $clsCategory->get_menu_link_category();
    foreach($arr_link as $v){
		$items[$v->title_alias] = array(
	        'title' => t('Danh mục'),
	        'page callback' => 'menu_page_router',
	        'access callback' => TRUE,
	        'type' => MENU_CALLBACK,
	    );
	}
	#products
	$items['san-pham'] = array(
        'title' => t('Sản phẩm'),
        'page callback' => 'get_list_item_product_full',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['san-pham-re-nhat'] = array(
        'title' => t('Sản phẩm'),
        'page callback' => 'get_list_item_product_full',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['san-pham-tot-nhat'] = array(
        'title' => t('Sản phẩm'),
        'page callback' => 'get_list_item_product_full',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['tim-kiem'] = array(
        'title' => t('Sản phẩm'),
        'page callback' => 'get_list_item_product_search',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    #statics
	$items['gioi-thieu'] = array(
        'title' => t('Giới thiệu'),
        'page callback' => 'pageIntro',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['tuyen-dai-ly'] = array(
        'title' => t('Tuyển đại lý'),
        'page callback' => 'pageDelivery',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
	$items['lien-he'] = array(
        'title' => t('Liên hệ'),
        'page callback' => 'pageContact',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['vote'] = array(
        'title' => t('Vote'),
        'page callback' => 'loadAjaxVote',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['thanks-order'] = array(
        'title' => t('Cảm ơn bạn đã mua hàng'),
        'page callback' => 'pageThanksOrder',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
     $items['huong-dan-mua-hang'] = array(
        'title' => t('Hướng dẫn mua hàng'),
        'page callback' => 'pageGuideBuy',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    #shop cart
    $items['shop-cart'] = array(
        'title' => t('Tất cả các sản phẩm trong giỏ hàng'),
        'page callback' => 'pagelistAllCart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['add-cart'] = array(
        'title' => t('Thêm vào giỏ hàng'),
        'page callback' => 'pageAddCart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['del-one-item-cart'] = array(
        'title' => t('Xóa 1 sản phẩm trong giỏ hàng'),
        'page callback' => 'pageDelOneItemInCart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
   $items['del-all-item-in-cart'] = array(
        'title' => t('Xóa tất cả sản phẩm trong giỏ hàng'),
        'page callback' => 'pageDelAllItemInCart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
   	$items['payment-cart'] = array(
        'title' => t('Thanh toán đơn hàng'),
        'page callback' => 'payOrderCart',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}
function HSSPageStatics_theme() {
	return array(
	    'page-product-full' => array(
	      'template' => 'View/tpl/page-product-full'
	    ),
	    'page-product-search' => array(
	      'template' => 'View/tpl/page-product-search'
	    ),
	    'page-product' => array(
	      'template' => 'View/tpl/page-product'
	    ),
	    'page-product-view' => array(
	      'template' => 'View/tpl/page-product-view'
	    ),
	    'page-news' => array(
	      'template' => 'View/tpl/page-news'
	    ),
	     'page-news-view' => array(
	      'template' => 'View/tpl/page-news-view'
	    ),
	    'page-intro' => array(
	      'template' => 'View/tpl/static/page-intro'
	    ),
		'page-delivery' => array(
	      'template' => 'View/tpl/static/page-delivery'
	    ),
		'page-contact' => array(
	      'template' => 'View/tpl/static/page-contact'
	    ),
        'page-guide-buy' => array(
          'template' => 'View/tpl/static/page-guide-buy'
        ),
	    'page-thanks-order' => array(
	      'template' => 'View/tpl/static/page-thanks-order'
	    ),
	    'page-list-shop-cart' => array(
	      'template' => 'View/tpl/shopcart/page-list-shop-cart'
	    ),
        'page-pay-cart' => array(
          'template' => 'View/tpl/shopcart/page-pay-cart'
        ),
	);
}
function HSSPageStatics_init() {
	$uri = request_uri();
	if(preg_match("/(\/admin)/", $uri)==0){
		$files = array(
			'Controller/HSSPageProductControler.php',
			'Controller/HSSPageNewsControler.php',
			'Controller/HSSPageStaticControler.php',
			'Controller/HSSPageShopCartControler.php'
		);
		clsLoader::load('HSSPageStatics', $files);
	}
}
function menu_page_router(){
	global $base_url;
	$param = arg();
	
	if(count($param) == 1 && $param[0] != ''){
		$clsCategory = new Category();
		$menu = $clsCategory->getCatFromAlias($param[0]);
		if(count($menu)>0){
			$type= $menu[0]->type_id;
			$catid= $menu[0]->id;
			if($type == 7 && $catid > 0){
				return get_list_item_product($type, $catid);
			}elseif($type == 8 && $catid > 0){
				return get_list_item_news($type, $catid);
			}
		}else{
			drupal_goto($base_url);
		}
	}elseif(count($param) == 2 && $param[1] != ''){
		$clsCategory = new Category();
		$menu = $clsCategory->getCatFromAlias($param[0]);
		if(count($menu)>0){
			$type= $menu[0]->type_id;
			$catid= $menu[0]->id;
			$title_alias = $param[1];
			if($type == 7 && $catid > 0){
				return get_item_product_view($title_alias, $catid);
			}elseif($type == 8 && $catid > 0 && $title_alias != ''){
				return get_item_new_view($title_alias, $catid);
			}
		}else{
			drupal_goto($base_url);
		}
	}else{
		drupal_goto($base_url);
	}
}